"""
AI handler for NyayAI - manages AI provider integrations and offline fallbacks
"""
import os
import json
from typing import Optional, Dict
from config import OFFLINE_RESPONSES, MODEL_CONFIG
from ai_providers import create_ai_provider, AIProvider

class AIHandler:
    def __init__(self):
        self.provider_type = os.environ.get("AI_PROVIDER", "gemini").lower()
        self.api_key = os.environ.get(f"{self.provider_type.upper()}_API_KEY", "")
        self.provider: Optional[AIProvider] = None
        self._initialize_ai()
    
    def _initialize_ai(self):
        """Initialize AI with current API key"""
        if self.api_key and self.api_key.strip():
            print(f"Initializing {self.provider_type.capitalize()} AI provider...")
            print(f"API Key length: {len(self.api_key.strip())}")
            self.provider = create_ai_provider(self.provider_type, self.api_key)
            if not self.provider:
                print(f"Failed to initialize {self.provider_type.capitalize()} provider. Please check your API key and try again.")
        else:
            print(f"No API key found for {self.provider_type.capitalize()} provider.")
    
    def update_configuration(self, provider_type: str, api_key: str) -> bool:
        """Update provider type and API key"""
        if not provider_type or not api_key or not api_key.strip():
            print("Provider type or API key is empty")
            return False
            
        try:
            # Clean the input
            self.provider_type = provider_type.lower().strip()
            self.api_key = api_key.strip()
            
            # Basic validation of API key format
            if self.provider_type == "openai" and not self.api_key.startswith("sk-"):
                print("Invalid OpenAI API key format. It should start with 'sk-'")
                return False
                
            # Update environment variables
            os.environ[f"{self.provider_type.upper()}_API_KEY"] = self.api_key
            os.environ["AI_PROVIDER"] = self.provider_type
            
            # Try to initialize the AI provider
            self._initialize_ai()
            
            # Verify the initialization worked
            is_available = self.is_online()
            if not is_available:
                print(f"Failed to initialize {self.provider_type} provider with the given API key")
            return is_available
            
        except Exception as e:
            print(f"Error configuring AI provider: {str(e)}")
            return False
    
    def is_online(self) -> bool:
        """Check if AI provider is available"""
        return self.provider is not None and self.provider.is_available()
    
    def validate_legal_query(self, query: str) -> tuple[bool, str]:
        """
        Validate if the query is related to legal matters.
        Returns a tuple of (is_legal, explanation/error_message)
        """
        if self.is_online():
            prompt = f"""
            You are NyayAI, an AI legal assistant specializing in Indian law.
            Your task is to determine if the following query is related to legal matters, specifically Indian law.
            
            User Query: {query}
            
            Validation criteria:
            1. Must be related to legal matters (law, rights, courts, police, crime, civil matters, etc.)
            2. Should be relevant to Indian context
            3. Can be about legal rights, procedures, IPC sections, or real-world legal scenarios
            4. Should not be general knowledge questions unrelated to law
            
            Respond in the following format:
            - If legal: "VALID: <brief explanation of legal relevance>"
            - If not legal: "INVALID: <explanation why it's not a legal query + suggestion to rephrase if possible>"
            
            Response:
            """
            response = self.provider.generate_content(prompt)
            if response:
                is_valid = response.strip().startswith("VALID:")
                message = response.strip().split(":", 1)[1].strip()
                return is_valid, message
            
        return True, ""  # Default to accepting in offline mode
    
    def add_disclaimer(self, response: str) -> str:
        """Add legal disclaimer to AI responses"""
        disclaimer = """
        
        ---
        **Important Disclaimer:** This response is generated by an AI system and should not be considered as professional legal advice. Laws and regulations can be complex and may vary based on jurisdiction and specific circumstances. For accurate legal guidance tailored to your situation, please consult with a qualified legal professional.
        """
        return response + disclaimer
    
    def generate_legal_response(self, query: str, context: str = "") -> str:
        """Generate response to legal query"""
        # First validate the query
        is_legal, validation_message = self.validate_legal_query(query)
        
        if not is_legal:
            return self.add_disclaimer(f"""I apologize, but I can only assist with legal-related queries. {validation_message}

If you believe your question is related to legal matters, please rephrase it explaining the legal context or connection to law.""")
        
        if self.is_online():
            # Optimized prompt for faster response with clear formatting
            context_brief = context.split('\n')[:3] if context else []  # Limit context to 3 most relevant sections
            prompt = f"""You are NyayAI, an Indian legal assistant. Provide a well-structured response.

Query: {query}
Relevant Laws: {' '.join(context_brief)}

Format your response EXACTLY as follows:

## 📋 Quick Answer
[Provide a clear, direct answer in 2-3 sentences that directly addresses the user's question]

## ⚖️ Legal Consequences
[Explain the legal implications, potential penalties, imprisonment terms, fines, or civil liabilities]

## 📜 Applicable Laws
[List relevant IPC sections, acts, and laws with brief explanations]
- **Section XXX IPC**: [Brief description]
- **Act Name**: [Brief description]

## 🛡️ What You Should Do
[Provide clear, numbered action steps]
1. **Step 1**: [Action to take]
2. **Step 2**: [Action to take]
3. **Step 3**: [Action to take]

## 💼 Legal Advice & Contacts
[Provide professional guidance on who to contact]
- **Immediate Action**: [What to do first]
- **Consult**: [Type of lawyer/professional needed]
- **Contact**: [Police station, legal aid, helpline numbers]

Keep response under 300 words. Use clear headings and bullet points."""
            
            response = self.provider.generate_content(prompt)
            if response:
                return self._format_response(response)
            
        return self._get_offline_response("default")
    
    def summarize_document(self, text: str) -> str:
        """Summarize legal document"""
        if self.is_online():
            # Limit text length to avoid token limits
            text_preview = text[:4000] if len(text) > 4000 else text
            
            prompt = f"""
            As NyayAI, provide a concise legal summary of this document.
            Focus on key legal points, obligations, rights, and important clauses.
            
            Document text: {text_preview}
            
            Provide:
            1. Document type identification
            2. Key parties involved
            3. Main legal obligations
            4. Important dates/deadlines
            5. Potential legal issues or concerns
            6. Recommendations for review
            
            Summary:
            """
            
            response = self.provider.generate_content(prompt)
            if response:
                return self.add_disclaimer(response)
            
        return self.add_disclaimer(self._get_offline_response("document"))
    
    def explain_ipc_section(self, section_data: Dict) -> str:
        """Explain IPC section in simple terms"""
        if self.is_online():
            prompt = f"""
            Explain IPC Section {section_data['section']} in simple, understandable terms for common people.
            
            Section: {section_data['section']}
            Title: {section_data['title']}
            Description: {section_data['description']}
            Category: {section_data['category']}
            Context: {section_data.get('context', 'Not available')}
            Punishment: {section_data.get('punishment', 'Not specified')}
            
            Provide:
            1. Simple explanation of what this law means
            2. Real-world examples of when it applies
            3. Potential punishments and legal consequences
            4. What to do if someone violates this law
            5. Related sections if applicable
            6. Practical advice for citizens
            
            Explanation:
            """
            
            response = self.provider.generate_content(prompt)
            if response:
                return self.add_disclaimer(response)
                
        return self.add_disclaimer(self._get_fallback_explanation(section_data))
    
    def _format_response(self, response: str) -> str:
        """Format AI response for better readability"""
        # Ensure response has proper markdown formatting
        formatted = response.strip()
        
        # Add spacing around headers if missing
        formatted = formatted.replace('##', '\n\n##')
        
        # Clean up extra whitespace
        while '\n\n\n' in formatted:
            formatted = formatted.replace('\n\n\n', '\n\n')
        
        return formatted.strip()
    
    def _get_fallback_explanation(self, section_data: Dict) -> str:
        """Get fallback explanation for IPC section"""
        explanation = f"**IPC Section {section_data['section']}: {section_data['title']}**\n\n"
        explanation += f"**Description:** {section_data['description']}\n\n"
        
        if 'context' in section_data:
            explanation += f"**When it applies:** {section_data['context']}\n\n"
        
        if 'punishment' in section_data:
            explanation += f"**Punishment:** {section_data['punishment']}\n\n"
        
        explanation += f"**Category:** {section_data['category']}\n\n"
        explanation += "*For detailed explanation and personalized legal advice, please configure your AI provider or consult with a qualified lawyer.*"
        
        return explanation
    
    def _get_offline_response(self, response_type: str) -> str:
        """Get offline fallback response"""
        return OFFLINE_RESPONSES.get(response_type, OFFLINE_RESPONSES["default"])
    
    def get_status_message(self) -> str:
        """Get current AI status message"""
        if self.is_online():
            return "🟢 **AI Online** - Full AI assistance available"
        else:
            return "🟡 **Offline Mode** - Basic assistance available. Configure your AI provider for full AI features."